name: piscine_data-science

services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    working_dir: /var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_network
    restart:
      unless-stopped
    environment:
      LC_COLLATE: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      POSTGRES_DB: piscineds
      POSTGRES_USER: blarger

volumes:
  postgres_data:

networks:
  app_network:
    name: app_network
    driver: bridge