name: piscine_data-science

services:

  exec:
    build:
      context: ./exec
      dockerfile: Dockerfile
    container_name: exec
    env_file: .env
    ports:
      - '8080:8080'
    expose:
      - 8080
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    env_file: .env
    ports: 
      - '5432:5432'
    expose:
      - 5432
    restart: always
    environment:
      LC_COLLATE: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      POSTGRES_DB: piscineds
      POSTGRES_USER: blarger
      POSTGRES_INITDB_ARGS: --data-checksums
      PGHOST: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: