name: piscine_data-science

services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    env_file: .env
    ports: 
      - '5432:5432'
    expose:
      - 5432
    restart: always
    environment:
      LC_COLLATE: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      POSTGRES_DB: piscineds
      POSTGRES_USER: blarger
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    name: app_network
    driver: bridge